server:
  servlet:
    context-path: /store
  port: 8189

spring:
  datasource:
    ddl-auto: update
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: root
    password: root
jpa:
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect